# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  - main

jobs:
- job: 'Lint'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'

  - script: |
      python -m pip install flake8
      flake8 --max-line-length=88
    displayName: 'Run lint tests'

- job: "Tests"
  pool:
    vmImage: "windows-latest"

  steps:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH

    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: "$(KNOWN_HOST)"
        sshPublicKey: "$(PUB_KEY)"
        sshKeySecureFile: "id_rsa"

    - task: UsePythonVersion@0
      inputs:
        versionSpec: "3.9"

    - task: Cache@2
      displayName: Cache Anaconda
      inputs:
        key: 'conda | "$(Agent.OS)" | environment.yml'
        path: $(CONDA)/envs
        cacheHitVar: CONDA_CACHE_RESTORED

    - script: conda env create --quiet --file environment.yml
      displayName: Create environment
      condition: eq(variables.CONDA_CACHE_RESTORED, 'false')

    - powershell: |
        conda run -n unittest dvc remote add --global -d azure azure://arcodatasets
        conda run -n unittest dvc remote modify --global azure connection_string $env:ARCODATASET_CONNECTION_STRING
        conda run -n unittest python tests/data/load_test_data.py
      env:
        ARCODATASET_CONNECTION_STRING: $(ARCODATASET_CONNECTION_STRING)
      displayName: "Download data"

    - script: |
        call activate unittest
        git clone git@ssh.dev.azure.com:v3/devsdb/CRD-NT_ARCO/rws2
        cd rws2
        pip install .
      displayName: "Install arco"

    - script: |
        call activate unittest
        python -m unittest discover tests
      displayName: "Run tests"
